### PR TITLE
ci: update docker release

### PR DESCRIPTION
**Pull request by matteo-cristino**
CI runs only on tags push

### CODE REVIEW

**Comment by Ignat99** [comment]
It would probably make sense to create a docker-compose file with all images, including [Planetmint](https://github.com/planetmint) and [Zenswarm Storage](https://forkbomb.solutions/component/zenswarm-storage/)?

**Comment by jaromil** [comment]
> It would probably make sense to create a docker-compose file with all images, including [Planetmint](https://github.com/planetmint) and [Zenswarm Storage](https://forkbomb.solutions/component/zenswarm-storage/) and [Fabchain](https://github.com/dyne/fabchain)?

These two projects are discontinued, as they didn't gain any traction among users. We only maintain generic integration now.

> Because tests need to be done on signed transactions and tokens (ERC 721, ERC 1155) with ready-made smart contracts. Unfortunately, I have not yet been able to find a ready-made example of using [these features](https://github.com/dyne/Zenroom/blob/master/test/ethereum/transfer_eth_plt.sh).

> The example above provides a ready-made contract without any explanation of what it looks like, where it is located, and how to assemble your own distributed data storage.

We have a ganache server running on a VPS which is used to test against. If you like to help us maintain it, that would be great. Its running as-is since a couple years with the contracts we test.

**Comment by Ignat99** [comment]
I have a docker-compose file for ganache with a tunnel via ssh for a remote graphical desktop. But I'm thinking about how to do it easier and more standard. But since I'm not an expert in Ethereum distributed databases specifically, I'm only studying how this is done standardly in Ethereum. Do I need an additional image for the data storage in addition to the existing boot node, RPC and miner?

**Comment by Ignat99** [comment]
> > It would probably make sense to create a docker-compose file with all images, including [Planetmint](https://github.com/planetmint) and [Zenswarm Storage](https://forkbomb.solutions/component/zenswarm-storage/) and [Fabchain](https://github.com/dyne/fabchain)?
> 
> These two projects are discontinued, as they didn't gain any traction among users. We only maintain generic integration now.
> 
> > Because tests need to be done on signed transactions and tokens (ERC 721, ERC 1155) with ready-made smart contracts. Unfortunately, I have not yet been able to find a ready-made example of using [these features](https://github.com/dyne/Zenroom/blob/master/test/ethereum/transfer_eth_plt.sh).
> 
> > The example above provides a ready-made contract without any explanation of what it looks like, where it is located, and how to assemble your own distributed data storage.
> 
https://github.com/dyne/Zenroom/blob/master/test/ethereum/create_erc721.sh#L52C27-L52C35

Here I clearly see a request to the test network Fabchain.

**Pull request merged**
