### PR TITLE
Remove hardcoded ar path

### PR DESCRIPTION
**Pull request by zzappie**
Tiny fix removing hardcoded path to "ar" executable

### CODE REVIEW

**Comment by zzappie** [comment]
Looking at travis logs... Can't figure out what is wrong...

The ar shell variable seems to be set adequately in configure.mk
But I find this .travis.yml line confusing:
```
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make win     && cp -v src/zenroom.exe build/ ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make win-dll && cp -v src/zenroom.dll build/ ; fi
```
Is it a typo?

**Comment by jaromil** [comment]
I have hardcoded that after many tries, long time ago. Not sure how it can be made better, but unless all tests pass I recommend not changing: by now there are many targets built by our CI and they could be affected.

**Comment by zzappie** [comment]
I think I got what was going on.

Cmake has a quirk that is hard to spot.  During cmake run it generates
commands and stores them in files to later run them.  In our case the
problem was in file `CMakeFiles/amcl_core.dir/link.txt`.  If you don't
specify the full path to `ar` it asumes that `ar` binary sits in project
root.  So `link.txt` file eds up looking like this:

```
/home/user/path/to/zenroom/lib/milagro-crypto-c/ar qc lib/libamcl_core.a  CMakeFiles/amcl_core.dir/src/hash.c.o CMakeFiles/amcl_core.dir/src/rand.c.o CMakeFiles/amcl_core.dir/src/randapi.c.o CMakeFiles/amcl_core.dir/src/aes.c.o CMakeFiles/amcl_core.dir/src/gcm.c.o CMakeFiles/amcl_core.dir/src/oct.c.o CMakeFiles/amcl_core.dir/src/utils.c.o CMakeFiles/amcl_core.dir/src/version.c.o CMakeFiles/amcl_core.dir/src/pbc_support.c.o CMakeFiles/amcl_core.dir/src/ecdh_support.c.o
/gnu/store/h5v73fvcx4gf9j2xi6xr80icbfjgwkdc-profile/bin/ranlib lib/libamcl_core.a
```

But the interesting thing is that, because `ar` path was hardcoded,
`/usr/bin/ar` was used in crosscompiling milargo to windows with no
problems. :)

So to fix ci I just needed to specify full path to
`x86_64-w64-mingw32-ar`...

**Comment by jaromil** [comment]
Many thanks for looking so deep into this! I've never been a fan of cmake and its quirks...

**Pull request merged**
