### PR TITLE
feat: create the eth abi decoding

### PR DESCRIPTION
**Pull request by albertolerda**

### CODE REVIEW

**Comment by jaromil** [comment]
Related to issue https://github.com/dyne/Zenroom/issues/681 we need to see if `used` is appropriate, perhaps better use `stored`?

**Comment by albertolerda** [comment]
It is actually quite different, the keyword "using", in this case, is used like in the statements `compose the secret using ''`, `create the ethereum abi encoding of '' using ''`, `create the jws signature using the ecdh signature in ''`, .... (it is not a verb, just specify a variable)

In the other PR, the keyword `use` is specific to ethereum and tells how to fill the field data/value of the `ethereum transaction` object

**Comment by andrea-dintino** [comment]
@jaromil we use the keyword 'using' in 7 statements already (include scenario 'secshare'):

https://gyazo.com/a481c21abcae97030f88a8b5391e7c6f

**Comment by jaromil** [comment]
ACK! thanks

**Pull request merged**
