### PR TITLE
fix: Add build directory for cmake

### LINKED ISSUE #145: make cortex-arm fail on master (57a5315) and v1.0.5
cannot make that instructions work, particularly the `make arm-cortex` step https://dev.zenroom.org/#/pages/cortex

I am in a debian 10 stable 4.19.0-13-amd64

installed dependencies

```
apt-get install -y git build-essential cmake zsh xxd gcc-arm-none-eabi
```

build instructions:

```
git clone https://github.com/dyne/Zenroom.git
cd Zenroom
#git tag 
git checkout v1.0.5
git submodule update --init --recursive
make cortex-arm
```

error details:

```
[ 30%] Linking C static library lib/libamcl_bls_BLS461.a
/usr/bin/cmake -P CMakeFiles/amcl_bls_BLS461.dir/cmake_clean_target.cmake
/usr/bin/cmake -E cmake_link_script CMakeFiles/amcl_bls_BLS461.dir/link.txt --verbose=1
/usr/bin/ar qc lib/libamcl_bls_BLS461.a  CMakeFiles/amcl_bls_BLS461.dir/src/bls_BLS461.c.obj
/usr/bin/arm-none-eabi-ranlib lib/libamcl_bls_BLS461.a
make[3]: Leaving directory '/home/user/dev/Zenroom/lib/milagro-crypto-c'
[ 30%] Built target amcl_bls_BLS461
make -f test/CMakeFiles/test_bls_sss_BLS461.dir/build.make test/CMakeFiles/test_bls_sss_BLS461.dir/depend
make[3]: Entering directory '/home/user/dev/Zenroom/lib/milagro-crypto-c'
cd /home/user/dev/Zenroom/lib/milagro-crypto-c && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/user/dev/Zenroom/lib/milagro-crypto-c /home/user/dev/Zenroom/lib/milagro-crypto-c/test /home/user/dev/Zenroom/lib/milagro-crypto-c /home/user/dev/Zenroom/lib/milagro-crypto-c/test /home/user/dev/Zenroom/lib/milagro-crypto-c/test/CMakeFiles/test_bls_sss_BLS461.dir/DependInfo.cmake --color=
Dependee "/home/user/dev/Zenroom/lib/milagro-crypto-c/test/CMakeFiles/test_bls_sss_BLS461.dir/DependInfo.cmake" is newer than depender "/home/user/dev/Zenroom/lib/milagro-crypto-c/test/CMakeFiles/test_bls_sss_BLS461.dir/depend.internal".
Dependee "/home/user/dev/Zenroom/lib/milagro-crypto-c/test/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/user/dev/Zenroom/lib/milagro-crypto-c/test/CMakeFiles/test_bls_sss_BLS461.dir/depend.internal".
Scanning dependencies of target test_bls_sss_BLS461
make[3]: Leaving directory '/home/user/dev/Zenroom/lib/milagro-crypto-c'
make -f test/CMakeFiles/test_bls_sss_BLS461.dir/build.make test/CMakeFiles/test_bls_sss_BLS461.dir/build
make[3]: Entering directory '/home/user/dev/Zenroom/lib/milagro-crypto-c'
[ 31%] Building C object test/CMakeFiles/test_bls_sss_BLS461.dir/test_bls_sss_BLS461.c.obj
cd /home/user/dev/Zenroom/lib/milagro-crypto-c/test && /usr/bin/arm-none-eabi-gcc -DCMAKE -I/home/user/dev/Zenroom/lib/milagro-crypto-c/include  -DARCH_CORTEX -mcpu=cortex-m4 -mthumb -mlittle-endian -mthumb-interwork -Wstack-usage=1024 -DLIBRARY -Wno-main -ffreestanding -nostartfiles -std=c99 -static-libgcc -Wall -Wextra -Wno-strict-prototypes -Wunused-value -Wcast-align -Wunused-variable -Wundef -Wformat-security -Wshadow -O2   -o CMakeFiles/test_bls_sss_BLS461.dir/test_bls_sss_BLS461.c.obj   -c /home/user/dev/Zenroom/lib/milagro-crypto-c/test/test_bls_sss_BLS461.c
/home/user/dev/Zenroom/lib/milagro-crypto-c/test/test_bls_sss_BLS461.c: In function 'main':
/home/user/dev/Zenroom/lib/milagro-crypto-c/test/test_bls_sss_BLS461.c:242:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/user/dev/Zenroom/lib/milagro-crypto-c/test/test_bls_sss_BLS461.c: In function 'test':
/home/user/dev/Zenroom/lib/milagro-crypto-c/test/test_bls_sss_BLS461.c:45:5: warning: stack usage might be 4512 bytes [-Wstack-usage=]
 int test(csprng *RNG)
     ^~~~
[ 32%] Linking C executable ../bin/test_bls_sss_BLS461
cd /home/user/dev/Zenroom/lib/milagro-crypto-c/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_bls_sss_BLS461.dir/link.txt --verbose=1
/usr/bin/arm-none-eabi-gcc  -DARCH_CORTEX -mcpu=cortex-m4 -mthumb -mlittle-endian -mthumb-interwork -Wstack-usage=1024 -DLIBRARY -Wno-main -ffreestanding -nostartfiles -std=c99 -static-libgcc -Wall -Wextra -Wno-strict-prototypes -Wunused-value -Wcast-align -Wunused-variable -Wundef -Wformat-security -Wshadow -O2   CMakeFiles/test_bls_sss_BLS461.dir/test_bls_sss_BLS461.c.obj  -o ../bin/test_bls_sss_BLS461 ../lib/libamcl_bls_BLS461.a ../lib/libamcl_pairing_BLS461.a ../lib/libamcl_curve_BLS461.a ../lib/libamcl_core.a 
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000008000
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-sbrkr.o): in function `_sbrk_r':
/tmp/building/package/build/arm-none-eabi/thumb/v7e-m/newlib/libc/reent/../../../../../../../newlib/libc/reent/sbrkr.c:51: undefined reference to `_sbrk'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-writer.o): in function `_write_r':
/tmp/building/package/build/arm-none-eabi/thumb/v7e-m/newlib/libc/reent/../../../../../../../newlib/libc/reent/writer.c:49: undefined reference to `_write'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-closer.o): in function `_close_r':
/tmp/building/package/build/arm-none-eabi/thumb/v7e-m/newlib/libc/reent/../../../../../../../newlib/libc/reent/closer.c:47: undefined reference to `_close'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-fstatr.o): in function `_fstat_r':
/tmp/building/package/build/arm-none-eabi/thumb/v7e-m/newlib/libc/reent/../../../../../../../newlib/libc/reent/fstatr.c:55: undefined reference to `_fstat'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-isattyr.o): in function `_isatty_r':
/tmp/building/package/build/arm-none-eabi/thumb/v7e-m/newlib/libc/reent/../../../../../../../newlib/libc/reent/isattyr.c:52: undefined reference to `_isatty'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-lseekr.o): in function `_lseek_r':
/tmp/building/package/build/arm-none-eabi/thumb/v7e-m/newlib/libc/reent/../../../../../../../newlib/libc/reent/lseekr.c:49: undefined reference to `_lseek'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/lib/thumb/v7e-m/libc.a(lib_a-readr.o): in function `_read_r':
/tmp/building/package/build/arm-none-eabi/thumb/v7e-m/newlib/libc/reent/../../../../../../../newlib/libc/reent/readr.c:49: undefined reference to `_read'
collect2: error: ld returned 1 exit status
make[3]: *** [test/CMakeFiles/test_bls_sss_BLS461.dir/build.make:88: bin/test_bls_sss_BLS461] Error 1
make[3]: Leaving directory '/home/user/dev/Zenroom/lib/milagro-crypto-c'
make[2]: *** [CMakeFiles/Makefile2:1284: test/CMakeFiles/test_bls_sss_BLS461.dir/all] Error 2
make[2]: Leaving directory '/home/user/dev/Zenroom/lib/milagro-crypto-c'
make[1]: *** [Makefile:163: all] Error 2
make[1]: Leaving directory '/home/user/dev/Zenroom/lib/milagro-crypto-c'
make: *** [Makefile:115: milagro] Error 2
```

### PR DESCRIPTION
**Pull request by splasky**
The source code and the build code are mixed together. This
will produce some errors during compiling.

This commit adds a build directory for cmake.
To avoid mixing the source code and the build code together.

### CODE REVIEW

**Comment by andrea-dintino** [comment]
Thanks @splasky , 
and have you tested if the build actually works?

**Comment by jserv** [comment]
This patch consists of the modifications for both build system and Cortex-M specific fixes. It would better to decouple the generic build system changes and the rest.

**Comment by splasky** [comment]
@andrea-dintino , Yes I tested on my computer(ubuntu 20.04LTS) with arm-none-eabi-gcc 9.2.1.
Would you like me to send you a github action for testing the cortex-arm build command?

**Comment by splasky** [comment]
Thanks for @jserv reply. I would separate this PR for build system and Cortex-M specific fixes.

**Comment by andrea-dintino** [comment]
> @andrea-dintino , Yes I tested on my computer(ubuntu 20.04LTS) with arm-none-eabi-gcc 9.2.1.
> Would you like me to send you a github action for testing the cortex-arm build command?

yes please, we'd be happy to add it in the documentation :-)

**Pull request merged**
